### ISSUE TITLE
Throw exceptions or provide a way to retrieve errors

### ISSUE THREAD

**Issue by AnnoyingTechnology** [polyfony-inc/google#1]
Cc @WarenN   

Le problème des exceptions, c'est que ça va casser le code existant.
Si on est prêt à faire les màj de bloc logique try/catch partout, why not

**Comment by WarenN** [comment]
C'est pour cela que je verrais plus une méthode plus douce

**Comment by AnnoyingTechnology** [comment]
Ok, je propose des Exceptions pour les évenement innatendus et de type erreur au cours du dev. Et retour de false avec method pour obtenir l'erreur, dans le cas d'une erreur fournie par l'api elle même.

Ex, 
* si on a pas de json dans le retour -> exception
* si on a un 400, 403 ou autre, càd clé incorrect, etc -> exception
* si on a du json et que l'api nous retourne un message d'erreur -> false + message

**Comment by WarenN** [comment]
oui c'est bien
